# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum, auto

class BlockInfo:
    r"""
    A single MDF block discovered while walking the file's link graph.
    
    Attributes
    ----------
    offset, end_offset, size : int
        On-disk byte range of the block.
    block_type : str
        Four-character MDF block tag (e.g. ``"##HD"``, ``"##CN"``).
    description : str
        Short human-readable summary (e.g. ``"channel 'Speed' [f64@0..8]"``).
    links : list[LinkInfo]
        Outbound links to other blocks.
    extra : Optional[str]
        Block-type-specific extra information, when applicable.
    """
    offset: builtins.int
    end_offset: builtins.int
    size: builtins.int
    block_type: builtins.str
    description: builtins.str
    links: builtins.list[LinkInfo]
    extra: typing.Optional[builtins.str]
    def __repr__(self) -> builtins.str:
        ...


class ChannelInfo:
    r"""
    Read-only metadata describing a single channel.
    
    Found on :py:attr:`GroupInfo.channels`, and returned by
    :py:meth:`Mdf.channel` / :py:meth:`MdfIndex.channel`.
    
    Attributes
    ----------
    name : Optional[str]
        Channel name from the ``##TX`` block, or ``None`` if not set.
    unit : Optional[str]
        Engineering unit string, or ``None``.
    comment : Optional[str]
        Free-form comment, or ``None``. Always ``None`` when obtained via the
        index (not stored in `IndexedChannel`).
    data_type : DataType
        The MDF data type of the raw samples.
    bit_count : int
        Width of the raw value in bits (e.g. 32 for f32, 64 for f64/u64).
    """
    name: typing.Optional[builtins.str]
    unit: typing.Optional[builtins.str]
    comment: typing.Optional[builtins.str]
    data_type: DataType
    bit_count: builtins.int
    is_master: builtins.bool
    is_vlsd: builtins.bool
    def __str__(self) -> builtins.str:
        ...

    def __repr__(self) -> builtins.str:
        ...


class DataType:
    r"""
    MDF channel data type descriptor.
    
    Wraps the on-disk MDF 4 data type code (`cn_data_type`) together with a
    human-readable name. Use the ``create_data_type_*`` helper functions to
    construct one for the writer API.
    
    Attributes
    ----------
    name : str
        Symbolic name, e.g. ``"FloatLE"``, ``"UnsignedIntegerLE"``.
    value : int
        The MDF spec numeric code (0-16, or 255 for unknown).
    """
    name: builtins.str
    value: builtins.int
    def __str__(self) -> builtins.str:
        ...

    def __repr__(self) -> builtins.str:
        ...


class FileLayout:
    r"""
    Full structural layout of an MDF file: blocks, links, and gaps.
    
    Build one with :py:meth:`from_file` or :py:meth:`Mdf.file_layout`. Use
    it to debug file structure, audit storage efficiency, or render a
    human-readable map of an MDF.
    """
    file_size: builtins.int
    blocks: builtins.list[BlockInfo]
    gaps: builtins.list[GapInfo]
    @staticmethod
    def from_file(path:builtins.str) -> FileLayout:
        r"""
        Build a layout by parsing an MDF file from disk.
        
        Parameters
        ----------
        path : str
        """
        ...

    def to_text(self) -> builtins.str:
        r"""
        Render the layout as a flat, sorted text listing.
        
        Each line is ``offset .. end_offset  block_type  description``,
        including link targets — easy to ``grep`` / diff.
        """
        ...

    def to_tree(self) -> builtins.str:
        r"""
        Render the link graph as an indented tree rooted at ``##ID``.
        """
        ...

    def to_json(self) -> builtins.str:
        r"""
        Serialize the layout to a pretty-printed JSON string.
        """
        ...

    def write_text_to_file(self, path:builtins.str) -> None:
        r"""
        Write the flat text listing (see :py:meth:`to_text`) to ``path``.
        """
        ...

    def write_tree_to_file(self, path:builtins.str) -> None:
        r"""
        Write the indented tree view (see :py:meth:`to_tree`) to ``path``.
        """
        ...

    def write_json_to_file(self, path:builtins.str) -> None:
        r"""
        Write the JSON representation (see :py:meth:`to_json`) to ``path``.
        """
        ...

    def __repr__(self) -> builtins.str:
        ...


class GapInfo:
    r"""
    A range of bytes in the file not covered by any visited block.
    
    Gaps usually represent alignment padding, abandoned scratch space, or
    (rarely) blocks that aren't reachable from the link graph.
    
    Attributes
    ----------
    start, end, size : int
    """
    start: builtins.int
    end: builtins.int
    size: builtins.int
    def __repr__(self) -> builtins.str:
        ...


class GroupInfo:
    r"""
    Read-only metadata describing a channel group (``##CG`` block).
    
    Returned by :py:attr:`Mdf.groups` / :py:attr:`MdfIndex.groups`.
    
    Attributes
    ----------
    name : Optional[str]
        Group / acquisition name (often ``None`` for files written by mf4-rs).
    comment : Optional[str]
        Free-form comment.
    channel_count : int
        Number of channels in this group.
    record_count : int
        Number of records (cycles) recorded for this group.
    """
    name: typing.Optional[builtins.str]
    comment: typing.Optional[builtins.str]
    channel_count: builtins.int
    record_count: builtins.int
    channels: builtins.list[ChannelInfo]
    channel_names: builtins.list[builtins.str]
    def channel(self, name:builtins.str) -> typing.Optional[ChannelInfo]:
        r"""
        Find a channel in this group by name (first match), or ``None``.
        """
        ...

    def __str__(self) -> builtins.str:
        ...

    def __repr__(self) -> builtins.str:
        ...


class LinkInfo:
    r"""
    A single outbound link from a block to another block.
    
    Attributes
    ----------
    name : str
        Link's role inside the source block (e.g. ``"first_dg_addr"``).
    target : int
        Absolute file offset of the target block (0 means null link).
    target_type : Optional[str]
        Block type at the target offset, when known (e.g. ``"##DG"``).
    """
    name: builtins.str
    target: builtins.int
    target_type: typing.Optional[builtins.str]
    def __repr__(self) -> builtins.str:
        ...


class Mdf:
    r"""
    Read-only handle to an MDF 4 file, backed by a memory-mapped buffer.
    
    Metadata (block tree, channel names, conversions) is parsed up front, but
    sample data is only decoded when you call :py:meth:`read`, :py:meth:`read_raw`
    or :py:meth:`series`. Navigate by group / channel **name** — there are no
    numeric indices in the public API.
    
    Example
    -------
    >>> import mf4_rs
    >>> mdf = mf4_rs.Mdf("recording.mf4")
    >>> for group in mdf.groups:
    ...     print(group.name, group.record_count, group.channel_names)
    >>> speed = mdf["Speed"]                 # numpy float64 array
    >>> rpm   = mdf.read("RPM", group="Engine")
    >>> s     = mdf.series("Speed")          # pandas Series, datetime index
    """
    groups: builtins.list[GroupInfo]
    channel_names: builtins.list[builtins.str]
    def __new__(cls,path:builtins.str): ...
    def group(self, name:builtins.str) -> typing.Optional[GroupInfo]:
        r"""
        Find a channel group by name (first match), or ``None``.
        """
        ...

    def channel(self, name:builtins.str) -> typing.Optional[ChannelInfo]:
        r"""
        Find a channel by name across all groups (first match), or ``None``.
        """
        ...

    def read(self, name:builtins.str, group:typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Read a channel as a ``pandas.Series`` of values indexed by timestamps.
        
        This is the primary read: the channel's samples (with all conversions
        applied) are the data, and the group's master/time channel is the index
        — a ``DatetimeIndex`` when the file has a start time, otherwise the raw
        master seconds. If there is no master, or the requested channel *is* the
        master, a default integer index is used.
        
        Parameters
        ----------
        name : str
            Channel name (case-sensitive).
        group : Optional[str]
            Restrict the search to a single group by name. Use this when the
            same channel name (e.g. ``"Time"``) appears in several groups.
        
        Raises
        ------
        MdfException
            If no matching channel exists or pandas is not installed.
        """
        ...

    def values(self, name:builtins.str, group:typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Read a numeric channel by name as a plain numpy ``float64`` array.
        
        The fast, pandas-free path — just the values, no timestamp index.
        Invalid / non-numeric samples are ``NaN``. Use :py:meth:`read` when you
        want the timestamp-indexed Series and faithful (text / table) conversions.
        
        Parameters
        ----------
        name : str
        group : Optional[str]
        """
        ...

    def __getitem__(self, key:typing.Any) -> typing.Any:
        r"""
        ``mdf["Speed"]`` — shorthand for :py:meth:`read` (timestamp-indexed Series).
        
        Pass a ``(name, group)`` tuple to disambiguate a channel name shared by
        several groups, e.g. ``mdf["Speed", "Engine"]``.
        """
        ...

    def file_layout(self) -> FileLayout:
        r"""
        Build a :class:`FileLayout` describing every block in this file.
        
        Useful for debugging or analysing on-disk structure: offset, size,
        type, link targets and unreferenced gaps for each MDF block.
        """
        ...


class MdfIndex:
    r"""
    Lightweight, self-contained index over an MDF 4 file.
    
    An index records the byte ranges of each channel, fully resolves every
    conversion block, and serialises to JSON. Navigate it by **name**
    (:py:attr:`groups`, :py:meth:`group`, :py:meth:`channel`). It also remembers
    its data :py:attr:`source` (file path or URL); reading is lazy — the
    byte-range request happens on :py:meth:`read` / :py:meth:`values`, never at
    build time.
    
    **Limitation:** compressed (``##DZ``) data blocks are not supported.
    
    Example
    -------
    >>> idx = mf4_rs.MdfIndex.from_url("https://host/recording.mf4")  # only metadata fetched
    >>> speed = idx.read("Speed")            # pandas Series; range request happens now
    >>> rpm   = idx.values("RPM")            # numpy float64, no timestamp index
    >>> idx.save("recording.idx.json")
    >>> idx = mf4_rs.MdfIndex.load("recording.idx.json")
    >>> idx.source = "recording.mf4"         # re-attach a source after load
    >>> t = idx.read("Speed")
    """
    groups: builtins.list[GroupInfo]
    channel_names: builtins.list[builtins.str]
    file_size: builtins.int
    source: typing.Optional[builtins.str]
    @staticmethod
    def from_file(path:builtins.str) -> MdfIndex:
        r"""
        Build a fresh index by parsing an MDF file from disk.
        
        All conversions are resolved during construction so the index is fully
        self-contained afterwards.
        
        Parameters
        ----------
        path : str
            Path to a ``.mf4`` file.
        """
        ...

    @staticmethod
    def load(path:builtins.str) -> MdfIndex:
        r"""
        Load a previously saved JSON index (companion to :py:meth:`save`).
        
        The original MDF file is only needed later, when you actually read
        values via :py:meth:`open`.
        """
        ...

    @staticmethod
    def from_url(url:builtins.str, chunk_size:typing.Optional[builtins.int]) -> MdfIndex:
        r"""
        Build an index from an MDF file served over HTTP / S3 using range
        requests, without downloading the whole file.
        
        Issues range reads only for metadata blocks; sample data is never
        fetched. With the default 1 MiB read-ahead chunk a typical file
        collapses to a handful of HTTP requests regardless of size.
        
        Parameters
        ----------
        url : str
            ``http://`` / ``https://`` URL honouring ``Range`` requests.
        chunk_size : int, optional
            Metadata read-ahead chunk size in bytes (default 1 MiB).
        """
        ...

    def save(self, path:builtins.str) -> None:
        r"""
        Serialize the index to JSON at ``path`` (dependency-free).
        """
        ...

    def group(self, name:builtins.str) -> typing.Optional[GroupInfo]:
        r"""
        Find a channel group by name (first match), or ``None``.
        """
        ...

    def channel(self, name:builtins.str) -> typing.Optional[ChannelInfo]:
        r"""
        Find a channel by name across all groups (first match), or ``None``.
        """
        ...

    def groups_with_channel(self, name:builtins.str) -> builtins.list[builtins.str]:
        r"""
        Names of the groups that contain a channel called ``name``.
        
        Use this to disambiguate a channel name shared by several groups, then
        pass the chosen group to :py:meth:`read` / :py:meth:`values`.
        """
        ...

    def byte_ranges(self, name:builtins.str, group:typing.Optional[builtins.str]) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Byte ranges ``[(offset, length), ...]`` occupied by a channel.
        
        Accounts for the channel's record-layout position and data-block
        splitting. Power-user entry point for issuing your own partial reads.
        
        Parameters
        ----------
        name : str
        group : Optional[str]
            Disambiguate by group when the name is not unique.
        """
        ...

    def byte_ranges_for_records(self, name:builtins.str, start_record:builtins.int, record_count:builtins.int) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Byte ranges covering a record window ``[start, start+count)``.
        """
        ...

    def conversion_info(self, name:builtins.str) -> typing.Optional[builtins.dict[builtins.str, typing.Any]]:
        r"""
        Inspect the conversion attached to a channel (by name).
        
        Returns ``None`` if the channel has no conversion, otherwise a dict
        describing it (``conversion_type``, ``values``, ``resolved_texts``,
        ``formula`` …).
        """
        ...

    def set_source_prop(self, value:typing.Optional[builtins.str]) -> None:
        ...

    def set_source(self, value:typing.Optional[builtins.str]) -> None:
        r"""
        Attach (or clear) the data source used by :py:meth:`read` / :py:meth:`values`.
        
        A value starting with ``http://`` or ``https://`` is treated as a URL;
        anything else as a local file path. Pass ``None`` to clear.
        """
        ...

    def read(self, name:builtins.str, group:typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Read a channel as a ``pandas.Series`` of values indexed by timestamps.
        
        **Lazy:** the byte-range request to the attached source happens now, not
        when the index was built. Values carry all conversions; the index is the
        group master converted to a ``DatetimeIndex`` (or raw seconds / default
        index when there is no start time / master).
        
        Parameters
        ----------
        name : str
        group : Optional[str]
            Disambiguate by group when the channel name is not unique.
        
        Raises
        ------
        MdfException
            If no source is attached, the channel is missing, or pandas is absent.
        """
        ...

    def values(self, name:builtins.str, group:typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Read a numeric channel by name as a plain numpy ``float64`` array.
        
        Lazy fast path — just the values, no timestamp index, pandas-free.
        Invalid / non-numeric samples are ``NaN``.
        
        Parameters
        ----------
        name : str
        group : Optional[str]
        """
        ...

    def __getitem__(self, key:typing.Any) -> typing.Any:
        r"""
        ``index["Speed"]`` — shorthand for :py:meth:`read` (timestamp-indexed Series).
        
        Pass a ``(name, group)`` tuple to disambiguate a channel name shared by
        several groups, e.g. ``index["Speed", "Engine"]``.
        """
        ...


class MdfWriter:
    r"""
    Streaming writer for MDF 4 files.
    
    Build an MDF file in five logical steps:
    
    1. ``writer = mf4_rs.MdfWriter("out.mf4")``
    2. ``writer.init_mdf_file()`` — write ``##ID`` and ``##HD``.
    3. Define structure: :py:meth:`add_channel_group`, then any combination of
       :py:meth:`add_time_channel`, :py:meth:`add_float_channel`,
       :py:meth:`add_float32_channel`, :py:meth:`add_int_channel`, or the
       generic :py:meth:`add_channel`.
    4. Write data: :py:meth:`start_data_block`, then either
       :py:meth:`write_record` (one record at a time, ergonomic) or
       :py:meth:`write_columns_f64` / :py:meth:`write_columns` (bulk numpy,
       much faster), then :py:meth:`finish_data_block`.
    5. :py:meth:`finalize` — flushes and closes the file. The writer is
       unusable after this; calling any other method raises ``MdfException``.
    
    All identifiers (``cg_*`` for groups, ``ch_*`` for channels) are *opaque
    strings* — pass them back to subsequent methods, but don't try to parse
    them. Channels are auto-linked into a per-group linked list in the order
    they were added.
    
    Example
    -------
    >>> w = mf4_rs.MdfWriter("demo.mf4")
    >>> w.init_mdf_file()
    >>> cg = w.add_channel_group("group_0")
    >>> t = w.add_time_channel(cg, "Time")
    >>> y = w.add_float_channel(cg, "Speed")
    >>> w.start_data_block(cg)
    >>> for i in range(100):
    ...     w.write_record(cg, [
    ...         mf4_rs.create_float_value(i * 0.01),
    ...         mf4_rs.create_float_value(i * 1.5),
    ...     ])
    >>> w.finish_data_block(cg)
    >>> w.finalize()
    """
    def __new__(cls,path:builtins.str): ...
    def init_mdf_file(self) -> None:
        r"""
        Write the MDF identification (``##ID``) and header (``##HD``) blocks.
        
        Must be called exactly once, before adding any channel group.
        """
        ...

    def add_channel_group(self, name:typing.Optional[builtins.str]) -> builtins.str:
        r"""
        Append a new channel group (``##CG``) to the file.
        
        Parameters
        ----------
        name : Optional[str]
            Group acquisition name. Written as a ``##TX`` block referenced
            from the new ``##CG`` via ``acq_name_addr``. Pass ``None`` to
            leave it unset.
        
        Returns
        -------
        str
            Opaque group ID (e.g. ``"cg_0"``) — pass to subsequent
            ``add_channel`` / ``write_record`` / ``finish_data_block`` calls.
        """
        ...

    def set_channel_group_comment(self, group_id:builtins.str, comment:builtins.str) -> None:
        r"""
        Attach a comment / description to a channel group.
        
        Writes a ``##TX`` block holding ``comment`` and links it from the
        group's ``comment_addr`` field.
        """
        ...

    def add_channel(self, group_id:builtins.str, name:builtins.str, data_type:DataType) -> builtins.str:
        r"""
        Add a generic channel to a channel group, using the data type's
        natural bit width.
        
        The new channel is linked after the most recently added channel in
        the same group, and inherits its byte offset from the running record
        layout. For float channels this defaults to **32 bits** — use
        :py:meth:`add_float_channel` if you want 64-bit precision.
        
        Parameters
        ----------
        group_id : str
            ID returned by :py:meth:`add_channel_group`.
        name : str
            Channel name (written as a ``##TX`` block).
        data_type : DataType
            One of the values from the ``create_data_type_*`` helpers.
        
        Returns
        -------
        str
            Opaque channel ID (e.g. ``"ch_3"``).
        """
        ...

    def add_time_channel(self, group_id:builtins.str, name:builtins.str) -> builtins.str:
        r"""
        Add a 64-bit little-endian float channel and mark it as the group's
        master / time channel.
        
        Equivalent to :py:meth:`add_float_channel` followed by
        :py:meth:`set_time_channel`. Should typically be the **first** channel
        added to a group — subsequent channels will be linked after it.
        
        Parameters
        ----------
        group_id : str
        name : str
            Usually ``"Time"`` or ``"t"``.
        
        Returns
        -------
        str
            Channel ID.
        """
        ...

    def add_float_channel(self, group_id:builtins.str, name:builtins.str) -> builtins.str:
        r"""
        Add a 64-bit little-endian float (``f64``) data channel.
        
        Recommended default for scientific / numeric data. Use
        :py:meth:`add_float32_channel` when 32-bit precision is enough and
        file size matters.
        """
        ...

    def add_float32_channel(self, group_id:builtins.str, name:builtins.str) -> builtins.str:
        r"""
        Add a 32-bit little-endian float (``f32``) data channel.
        
        Halves the per-record size compared to :py:meth:`add_float_channel`
        at the cost of precision (~7 decimal digits).
        """
        ...

    def add_int_channel(self, group_id:builtins.str, name:builtins.str) -> builtins.str:
        r"""
        Add a 64-bit little-endian unsigned integer (``u64``) data channel.
        
        For signed integers, build a generic channel with
        :py:meth:`add_channel` and ``create_data_type_*`` helpers (or call
        directly with the raw :class:`DataType`).
        """
        ...

    def set_time_channel(self, channel_id:builtins.str) -> None:
        r"""
        Mark an existing channel as the group's master / time channel.
        
        Sets ``channel_type = 2`` and ``sync_type = 1`` on the underlying
        ``##CN`` block. Most users should prefer :py:meth:`add_time_channel`,
        which combines channel creation with this call.
        
        Parameters
        ----------
        channel_id : str
            ID returned by one of the ``add_*_channel`` methods.
        """
        ...

    def start_data_block(self, group_id:builtins.str) -> None:
        r"""
        Open a fresh ``##DT`` data block for a channel group.
        
        Must be called once after all channels have been added, before any
        :py:meth:`write_record` / :py:meth:`write_columns_f64` /
        :py:meth:`write_columns` for that group. The writer will
        automatically split into multiple ``##DT`` fragments at the 4 MB
        boundary, joined by a ``##DL`` block when you call
        :py:meth:`finish_data_block`.
        """
        ...

    def write_record(self, group_id:builtins.str, values:typing.Sequence[DecodedValue]) -> None:
        r"""
        Append a single record (one sample for each channel in the group).
        
        ``values`` must contain exactly one entry per channel, in the same
        order channels were added — typically the master channel first, then
        data channels. Each value is encoded according to its channel's data
        type (the variant of :class:`DecodedValue` is *not* re-checked, so
        passing the wrong variant will produce nonsense bytes).
        
        This call has Python-level overhead per value; for bulk numeric data,
        prefer :py:meth:`write_columns_f64` or :py:meth:`write_columns`.
        """
        ...

    def finish_data_block(self, group_id:builtins.str) -> None:
        r"""
        Close the open ``##DT`` block for a channel group.
        
        If the group's data exceeded the 4 MB block size and was split
        across multiple ``##DT`` fragments, this also writes the ``##DL``
        (data list) block linking them together. Call once per group after
        all records have been written, and before :py:meth:`finalize`.
        """
        ...

    def write_columns_f64(self, group_id:builtins.str, columns:typing.Sequence[typing.Any]) -> None:
        r"""
        Bulk-write all channels of a group from numpy ``float64`` arrays.
        
        Equivalent to writing every record in row order, but ~10× faster than
        looping over :py:meth:`write_record` because it avoids per-value
        Python-Rust crossings and ``DecodedValue`` boxing.
        
        Parameters
        ----------
        group_id : str
        columns : list[numpy.ndarray]
            One contiguous 1-D ``float64`` array per channel, in channel
            order. **All arrays must have identical length** — that length
            becomes the record count. The float values are converted to each
            channel's declared data type before encoding.
        
        Raises
        ------
        MdfException
            If an array is not contiguous, not ``float64``, or lengths
            mismatch.
        """
        ...

    def write_columns(self, group_id:builtins.str, columns:typing.Sequence[typing.Any], dtypes:typing.Sequence[builtins.str]) -> None:
        r"""
        Bulk-write all channels of a group from heterogeneous numpy arrays.
        
        Like :py:meth:`write_columns_f64` but accepts a per-column dtype, so
        integer / single-precision channels are written without an
        intermediate ``float64`` round-trip.
        
        Parameters
        ----------
        group_id : str
        columns : list[numpy.ndarray]
            One contiguous 1-D array per channel, all of identical length.
        dtypes : list[str]
            One entry per column, matching ``columns``. Allowed values:
            ``"f64"``, ``"f32"``, ``"u64"``, ``"i64"``.
        
        Raises
        ------
        MdfException
            If the dtype string is not one of the supported values, the
            numpy array's element type doesn't match the dtype string, the
            two list lengths differ, or any array is non-contiguous.
        """
        ...

    def finalize(self) -> None:
        r"""
        Flush all buffered bytes to disk and close the file.
        
        After this returns, the writer is consumed: any subsequent method
        call raises ``MdfException``. Calling :py:meth:`finalize` more than
        once also raises.
        """
        ...


class DecodedValue(Enum):
    r"""
    A single decoded channel sample, tagged with its underlying type.
    
    Returned by ``create_*_value`` helpers and consumed by
    :py:meth:`MdfWriter.write_record`. When *reading*, most APIs return native
    Python objects (``float`` / ``int`` / ``str`` / ``bytes``) directly, so you
    usually only construct ``DecodedValue`` to feed back into the writer.
    
    Variants carry a single ``value`` field (use the ``value`` getter to
    retrieve the inner native Python value):
    
    - ``Float(value: float)``
    - ``UnsignedInteger(value: int)``
    - ``SignedInteger(value: int)``
    - ``String(value: str)``
    - ``ByteArray(value: bytes)``
    - ``Unknown()`` — undecodable / not yet supported
    """
    Float = auto()
    UnsignedInteger = auto()
    SignedInteger = auto()
    String = auto()
    ByteArray = auto()
    Unknown = auto()

def create_data_type_float_le() -> DataType:
    r"""
    Return the :class:`DataType` for little-endian IEEE-754 floats.
    
    Pair with :py:meth:`MdfWriter.add_channel`. Defaults to 32 bits when
    passed to ``add_channel`` — for f64 use :py:meth:`MdfWriter.add_float_channel`.
    """
    ...

def create_data_type_string_utf8() -> DataType:
    r"""
    Return the :class:`DataType` for UTF-8 encoded string channels.
    """
    ...

def create_data_type_uint_le() -> DataType:
    r"""
    Return the :class:`DataType` for little-endian unsigned integers.
    
    Pair with :py:meth:`MdfWriter.add_channel` when you need an unsigned
    integer channel of non-default width (otherwise see
    :py:meth:`MdfWriter.add_int_channel`).
    """
    ...

def create_float_value(value:builtins.float) -> DecodedValue:
    r"""
    Wrap a Python ``float`` in a :class:`DecodedValue` of variant ``Float``.
    
    Use this to feed values into :py:meth:`MdfWriter.write_record` for any
    floating-point channel (32- or 64-bit; the value is truncated to the
    channel's declared bit width on encode).
    """
    ...

def create_int_value(value:builtins.int) -> DecodedValue:
    r"""
    Wrap a Python ``int`` in a ``SignedInteger`` :class:`DecodedValue`.
    """
    ...

def create_string_value(value:builtins.str) -> DecodedValue:
    r"""
    Wrap a Python ``str`` in a ``String`` :class:`DecodedValue`.
    
    For string channels (``StringUtf8`` etc.). Encoding into the file is
    done according to the channel's declared string data type.
    """
    ...

def create_uint_value(value:builtins.int) -> DecodedValue:
    r"""
    Wrap a Python ``int`` in a ``UnsignedInteger`` :class:`DecodedValue`.
    
    Suitable for any unsigned integer channel; the value is truncated to the
    channel's bit width on encode.
    """
    ...

def cut_mdf_by_time(input_path:builtins.str, output_path:builtins.str, start_time:builtins.float, end_time:builtins.float) -> None:
    r"""
    Cut an MDF file by time, copying only records whose master channel value
    falls within the inclusive `[start_time, end_time]` window.
    
    The output preserves fixed-length numeric, string, and byte-array
    channels, per-record invalidation bytes, and VLSD ("signal-based")
    channels (a fresh ##SD chain is written for each kept VLSD channel).
    Per-channel conversion / source / metadata blocks are not re-emitted, so
    the output channels read as raw values.
    
    Parameters
    ----------
    input_path : str
        Path to the source MF4 file.
    output_path : str
        Destination path for the trimmed file.
    start_time : float
        Start of the window in seconds (inclusive).
    end_time : float
        End of the window in seconds (inclusive).
    """
    ...

def cut_mdf_by_utc(input_path:builtins.str, output_path:builtins.str, start_utc:typing.Any, end_utc:typing.Any) -> None:
    r"""
    Cut an MDF file by absolute UTC time. Accepts ISO 8601 strings (e.g.
    `"2024-01-15T12:34:56Z"`), `datetime.datetime` objects (naive values are
    assumed to be UTC), or numeric UNIX timestamps in seconds.
    
    The window is inclusive on both ends. The source file must record a
    non-zero `HD.abs_time` (set by the writer / asammdf when creating the
    file) — without it the relative offset cannot be computed and an
    `MdfException` is raised.
    
    Other behaviour matches [`cut_mdf_by_time`]: VLSD payloads, byte-array
    channels, and per-record invalidation bytes are preserved verbatim.
    """
    ...

def file_layout_from_file(path:builtins.str) -> FileLayout:
    r"""
    Build a :class:`FileLayout` from an MDF file on disk.
    
    Functional alias for :py:meth:`FileLayout.from_file`.
    
    Parameters
    ----------
    path : str
    
    Returns
    -------
    FileLayout
    """
    ...

def merge_files(output:builtins.str, first:builtins.str, second:builtins.str) -> None:
    r"""
    Merge two MDF files into a new file at ``output``.
    
    Channel groups whose layouts (record-id length and channel list — names,
    data types, bit/byte offsets, bit count, channel type, VLSD flag) match
    are concatenated; non-matching groups are appended as separate groups.
    Supports normal numeric, fixed ``ByteArray``, and VLSD signal channels
    (variable-length strings and byte arrays stored in ``##SD`` blocks).
    
    Parameters
    ----------
    output : str
        Destination path for the merged file.
    first, second : str
        Source file paths. Must be uncompressed MDF 4.10+ files.
    """
    ...

