use mf4_rs::blocks::common::DataType;

pub struct ConstSig {
    pub name: &'static str,
    pub bit_count: u32,
    pub data_type: DataType,
    pub float_val: f32,
    pub int_val: i64,
}

pub const SIG_LIST: &[ConstSig] = &[
    ConstSig { name: "Sig01", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig02", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 112 },
    ConstSig { name: "Sig03", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 2 },
    ConstSig { name: "Sig04", bit_count: 16, data_type: DataType::FloatLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig05", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig06", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig07", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig08", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig09", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig10", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig11", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig12", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 1 },
    ConstSig { name: "Sig13", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig14", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig15", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 1 },
    ConstSig { name: "Sig16", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig17", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig18", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig19", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig20", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 2 },
    ConstSig { name: "Sig21", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig22", bit_count: 16, data_type: DataType::FloatLE, float_val: -20.48, int_val: 0 },
    ConstSig { name: "Sig23", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig24", bit_count: 16, data_type: DataType::FloatLE, float_val: -20.48, int_val: 0 },
    ConstSig { name: "Sig25", bit_count: 16, data_type: DataType::FloatLE, float_val: -20.48, int_val: 0 },
    ConstSig { name: "Sig26", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig27", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 1 },
    ConstSig { name: "Sig28", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig29", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig30", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 7 },
    ConstSig { name: "Sig31", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig32", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig33", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig34", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig35", bit_count: 3, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig36", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 2 },
    ConstSig { name: "Sig37", bit_count: 16, data_type: DataType::FloatLE, float_val: 0.2, int_val: 0 },
    ConstSig { name: "Sig38", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig39", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 3 },
    ConstSig { name: "Sig40", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig41", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 166 },
    ConstSig { name: "Sig42", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 1 },
    ConstSig { name: "Sig43", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 40.0, int_val: 0 },
    ConstSig { name: "Sig44", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 1 },
    ConstSig { name: "Sig45", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig46", bit_count: 16, data_type: DataType::FloatLE, float_val: -25575.0, int_val: 0 },
    ConstSig { name: "Sig47", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig48", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig49", bit_count: 16, data_type: DataType::FloatLE, float_val: 0.06, int_val: 0 },
    ConstSig { name: "Sig50", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 157 },
    ConstSig { name: "Sig51", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig52", bit_count: 2, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 3 },
    ConstSig { name: "Sig53", bit_count: 1, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig54", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 8 },
    ConstSig { name: "Sig55", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 131 },
    ConstSig { name: "Sig56", bit_count: 4, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
    ConstSig { name: "Sig57", bit_count: 8, data_type: DataType::UnsignedIntegerLE, float_val: 0.0, int_val: 0 },
];

pub const RAW_MSG: [u8; 64] = [
    0x70, 0x08, 0x23, 0x28, 0x02, 0x07, 0x08, 0x00, 0x00, 0xA6, 0x08, 0x00,
    0x07, 0x1E, 0x7A, 0x9D, 0x08, 0x0C, 0x03, 0x83, 0x08, 0x50, 0x42, 0x04,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x08, 0x08,
    0x01, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
];

// pub const RAW_MSG2: [u8; 64] = [
//     0x70, 0x08, 0x23, 0x28, 0x02, 0x07, 0x08, 0x00, 0x00, 0x76, 0x08, 0x00,
//     0x07, 0x7E, 0x7A, 0x7D, 0x08, 0x0C, 0x03, 0x73, 0x08, 0x50, 0x42, 0x04,
//     0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x08, 0x08,
//     0x01, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
//     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
//     0x00, 0x00, 0x00, 0x00,
// ];
